//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catched_Pokemon
    {
        public int Api_Version { get; set; }
        public string Name { get; set; }
        public string PrimaryType { get; set; }
        public string SecundaryType { get; set; }
        public string Image_Url { get; set; }
        public Nullable<int> Owner_Id { get; set; }
        public int Number { get; set; }
        public int Identifier { get; set; }
    }
}
