//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokemonEntities : DbContext
    {
        public PokemonEntities()
            : base("name=PokemonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catched_Pokemon> Catched_Pokemon { get; set; }
        public virtual DbSet<Pokemon_Trainer> Pokemon_Trainer { get; set; }

        public System.Data.Entity.DbSet<Pokemon_Trainer> PokemonTrainers { get; set; }
    }
}
